spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpashop_api
    username: jpa_user
    password: jpa_user123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
server:
  port: 8889
logging:
  level:
    org.hibernate.SQL: debug